#!/bin/sh

# A docker container running php to be used in vscode editor

# Give permissions --> chmod 755 /somewhere/php7wrapper
# save it as "php7_for_vscode" in Home directory


docker run \
    --rm \
    -i \
    --network=host \
    -v "$HOME":"$HOME":ro \
    -u $(id -u) \
    -w "$PWD" \
    --name Nodejs_used_by_vscode_editor \
    node:8-alpine \
    node
    # php "$@"

# exit $?
