module.exports = {
  sidebar: {
    "/documentation/": ["vuepress.md", "markdown.md", "it-basics.md"],
    "/windows10/": ["windows10.md", "wsl.md"],
    "/visual-studio-code/": [
      "vscode.md",
      "get-started.md",
      "user-guide.md",
      "language-javascript.md",
      "extensions.md",
      "settings.md",
    ],
    "/php/": [
      // "1 - Basic syntax & Data Types.md",
      "",
      "2 - Variables.md",
      "3 - Constants.md",
      "4 - Operators.md",
      "5 - Control Structures.md",
      "6 - Functions.md",
      "7 - Classes & Objects.md",
      "8 - Features - Cookies & Sessions.md",
      "Cryptography.md",
      "Deployment.md",
      "Php - The right way.md",
      "PSR Standards.md",
      "Testing.md",
    ],
    "/terminal/": ["Zsh.md", "Bash.md", "Bash-script.md", "WindowsTerminal.md"],
  },
};
